accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from accounts.views import Login, Logout, RegisterView, ConfirmView

app_name = 'accounts'


urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(next_page='/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/<uidb64>/<token>/', ConfirmView.as_view(), name='confirm'),
    #path('password_reset/', ConfirmView.as_view(), name='password_reset_confirm')
]

geography/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from geography.views import SignCreateView, WinesView, \
    CountryCreateView, RegionCreateView, AreaCreateView, QualityMarkCreateView, load_regions, IndexView

app_name = 'geography'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/sign', login_required(SignCreateView.as_view()), name='create_sign'),
    path('view/', login_required(WinesView.as_view()), kwargs={'slug': 'another_url'}, name='view'),
    path('create/country', login_required(CountryCreateView.as_view()), name='create_country'),
    path('create/region', login_required(RegionCreateView.as_view()), name='create_region'),
    path('create/area', login_required(AreaCreateView.as_view()), name='create_area'),
    path('create/quality_mark', login_required(QualityMarkCreateView.as_view()), name='create_quality_mark'),

    path('ajax/load-regions', load_regions, name='ajax_load_regions'),

]

wine/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from geography.views import IndexView, SearchResultsView

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('geo/', include('geography.urls', namespace='geo')),
    path('', include('accounts.urls')),
    path('', IndexView.as_view(template_name="index.html"), name='index'),
    path('', include('django.contrib.auth.urls')),  # необоходимо для сброса пароля и прочих auth-плюх
    path('search/', SearchResultsView.as_view(), name='search_results'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# Add Django site authentication urls (for login, logout, password management)
# urlpatterns += [
#     path('account/', include('django.contrib.auth.urls')),
# ]

geography/models.py
from django.db import models
from django.urls import reverse
from static.py.countries_list import COUNTRIES_LIST
from static.py.regions_list import REGIONS_LIST
from django.utils.translation import gettext_lazy as _


class Country(models.Model):
    """Common Country model"""
    class Meta:
        verbose_name_plural = "Countries"

    """Список развернул чтобы корректно отображалось в шаблоне, и корректно работал 
    поиск по неразвёрнутому списку"""
    COUNTRIES = [(item[0], item[1]) for item in COUNTRIES_LIST]
    name = models.CharField(_('Country name'), unique=True, choices=COUNTRIES, max_length=128)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('geo:view', kwargs={'pk': self.pk})


class Region(models.Model):
    """Common region model (depends on Country)"""
    class Meta:
        verbose_name_plural = "Regions"

    REGIONS = REGIONS_LIST
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(_('Region name'), max_length=128)

    def __str__(self):
        return self.name


class Area(models.Model):
    """Common area model (depends on region)"""
    class Meta:
        verbose_name_plural = "Areas"

    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(_('Area name'), max_length=128)

    def __str__(self):
        return self.name


class QualityMark(models.Model):
    """Common quality mark model (depends on Country, region and area)"""
    class Meta:
        verbose_name_plural = "Quality marks"

    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    name = models.CharField(_('Quality mark'), max_length=64)

    def __str__(self):
        return self.name


class Sign(models.Model):
    """Common "wine sign" model (depends on Country, region. area and quality mark)"""
    class Meta:
        verbose_name_plural = "Signs"

    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    quality_mark = models.ForeignKey(QualityMark, on_delete=models.CASCADE)
    sign = models.CharField(_('Wine sign'), max_length=1)
    name = models.CharField(_('Sign'), max_length=64)

    def __str__(self):
        return f'Sign {self.id} ({self.country}, {self.region}, {self.sign})'

geography/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, widgets
from django.urls import reverse_lazy

from geography.models import Country, Region, Area, QualityMark, Sign


class MySelectWidget(widgets.Select):

    template_name = 'forms/widgets/my_signform_select.html'

    def get_context(self, name, value, attrs):
        """Чтобы каждую ссылку (add new) не прописывать в шаблон -
        создал генерацию ссылок в контекст при отрисовке виджета
        по имени (важно, чтобы имя виджета совпадало с именем ссылки в urlconf).
        Переменная генерируется в контекст вышеуказанного шаблона"""
        context = super().get_context(name, value, attrs)
        context['add_link'] = reverse_lazy(f'geo:create_{name}')
        return context


class SignCreateForm(ModelForm):
    name = 'Sign creation form'
    button_label = 'SAVE'

    class Meta:
        model = Sign
        fields = ('country', 'region', 'area', 'quality_mark', 'sign')
        widgets = {'country': MySelectWidget,
                   'region': MySelectWidget,
                   'area': MySelectWidget,
                   'quality_mark': MySelectWidget}
    method = 'POST'
    process_url = reverse_lazy('geo:create_quality_sign')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

#  print(SignCreateForm.__mro__)


class CountryCreateForm(ModelForm):
    form_label = 'Country creation form'
    button_label = 'Save'

    class Meta:
        model = Country
        fields = '__all__'

    method = 'POST'
    process_url = reverse_lazy('geo:create_country')

    def __init__(self, *args, **kwargs):
        super(CountryCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegionCreateForm(ModelForm):
    form_label = 'Region creation form'
    button_label = 'Save'

    class Meta:
        model = Region
        fields = ('country', 'name')

    method = 'POST'
    process_url = reverse_lazy('geo:create_region')

    def __init__(self, *args, **kwargs):
        super(RegionCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class AreaCreateForm(ModelForm):
    form_label = 'Area creation form'
    button_label = 'Save'

    class Meta:
        model = Area
        fields = ('name', 'region')

    method = 'POST'
    process_url = reverse_lazy('geo:create_area')

    def __init__(self, *args, **kwargs):
        super(AreaCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class QualityMarkCreateForm(ModelForm):
    form_label = 'Quality mark creation form'
    button_label = 'Save'

    class Meta:
        model = QualityMark
        fields = '__all__'

    method = 'POST'
    process_url = reverse_lazy('geo:create_quality_mark')

    def __init__(self, *args, **kwargs):
        super(QualityMarkCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


"""
class RegionForm(ModelForm):
    class Meta:
        model = Region
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(RegionForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['name'].queryset = Region.objects.filter(country=Country.name)
"""


class LoginForm(AuthenticationForm):
    form_label = 'Login form'

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'login_field_form'  # это чтобы Bootstrap работал

geography/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView

from core.forms import SearchForm
from geography.forms import SignCreateForm, CountryCreateForm, RegionCreateForm, \
    AreaCreateForm, QualityMarkCreateForm
from geography.models import Sign, Country, Region, Area, QualityMark
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


class IndexView(TemplateView):
    """Generic class for index page rendering"""
    template_name = "index.html"


def load_regions(request):
    """Function for dynamic loading fields of sign creation form"""

    country_id = request.POST.get('countryId')
    region_id = request.POST.get('regionId')
    area_id = request.POST.get('areaId')

    regions = Region.objects.filter(country_id=country_id).order_by('name')
    areas = Area.objects.filter(region_id=region_id).order_by('name')
    quality_marks = QualityMark.objects.filter(area_id=area_id).order_by('name')
    context = {
        'country_id': country_id,
        'region_id': region_id,
        'regions': regions,
        'areas': areas,
        'quality_marks': quality_marks,
    }
    return render(request, 'inc/dropdown_list_country.html', context)


class SignCreateView(PermissionRequiredMixin, CreateView):
    """Generic class for sign creation form rendering"""
    template_name = "create_sign.html"
    model = Sign
    form_class = SignCreateForm
    success_url = reverse_lazy('geo:create_sign')
    permission_required = 'accounts.create_sign'  # во-вторых, у пользователя должно быть отдельное право на создание

    def get_context_data(self, **kwargs):  # добавление сортированного списка разрешений для текущего пользователя
        context = super().get_context_data(**kwargs)
        perms = list(self.request.user.get_user_permissions())
        # for item in set(self.request.user.get_user_permissions()):
        #     print(item)
        current_permissions = [w.replace('.', ' - ').replace('_', ' ') for w in sorted(perms)]
        context['current_permissions'] = current_permissions
        return context


class CountryCreateView(CreateView):
    """Generic class for country creation form rendering"""
    template_name = "create_country.html"
    model = Country
    form_class = CountryCreateForm
    success_url = reverse_lazy('geo:create_country')


class RegionCreateView(CreateView):
    """Generic class for region creation form rendering"""
    template_name = "create_region.html"
    model = Region
    form_class = RegionCreateForm
    success_url = reverse_lazy('geo:create_region')


class AreaCreateView(CreateView):
    """Generic class for area creation form rendering"""
    template_name = "create_area.html"
    model = Area
    form_class = AreaCreateForm
    success_url = reverse_lazy('geo:create_area')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['country'] = Country
        return context


class QualityMarkCreateView(CreateView):
    """Generic class for quality mark creation form rendering"""
    template_name = "create_quality_mark.html"
    model = QualityMark
    form_class = QualityMarkCreateForm
    success_url = reverse_lazy('geo:create_area')


class WinesView(ListView):
    """Generic class for wines list page rendering"""
    model = Sign
    fields = '__all__'
    template_name = 'view.html'
    context_object_name = 'articles'  # template variable for pagination

    def get_queryset(self):
        """Paginator test (lists by 1 item)"""
        if self.request.user.active:
            articles = Sign.objects.all()
            paginator = Paginator(articles, 1)
            page = self.request.GET.get('page')
            try:
                articles = paginator.page(page)
            except PageNotAnInteger:
                # Returns first page if page is not an integer.
                articles = paginator.page(1)
            except EmptyPage:
                # Returns last page of results if page is out of range (e.g. 9999)
                articles = paginator.page(paginator.num_pages)
            return articles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.active:
            context['form'] = SearchForm
            return context
        else:
            context['error_msg'] = 'Для испольования базы Вам необходимо активировать свою учетную запись!'
            return context


class SearchResultsView(ListView):
    """Simple database search"""
    model = Sign
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('search_field')
        print(Sign.objects.all())
        object_list = Sign.objects.filter(
            Q(name__icontains=query) |
            Q(quality_mark__country__name__icontains=query) |
            Q(quality_mark__area__name__icontains=query)
        )
        return object_list

geography/templates/base.html
{% load static %}{% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
{% trans 'Wine database site' %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
</head>
<body>
{% block head %}
{% endblock %}

{% block body %}
{% for message in messages %}
    {{ message }}
{% endfor %}
{% endblock %}
</body>
<script language="JavaScript" type="text/javascript" src="{% static 'js/test_cascade.js' %}"></script>
{#<script type="text/javascript" src="{% static 'js/country_straight_cascade.js' %}"></script>#}

geography/templates/create_area.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your edit.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}

{% include 'inc/uni_form.html' %}

{% endblock %}

geography/templates/create_country.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your edit.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}

{% include 'inc/uni_form.html' %}

{% endblock %}

geography/templates/create_quality_mark.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your edit.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}


<form method="post" id="signForm" data-regions-url="{% url 'geo:ajax_load_regions' %}" novalidate> <!-- necessary -->
{% include 'inc/uni_form.html' %}
</form>

{% endblock %}

geography/templates/create_region.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your edit.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}

{% include 'inc/uni_form.html' %}

{% endblock %}

geography/templates/create_sign.html
{% extends "base.html" %}{% load i18n %}
{% load static my_template_tag %}
{% block body %}
    <p>{% trans 'This is create_sign.html'|yell %}</p>
    <a href="{% url 'index' %}">Back to Index</a>
    {% include "inc/include.html" %}
<div style="width: 50%; margin: auto">
    {{ current_date }}
{% if perms %}
    <p style="float: right">{% trans 'List of your current permissions:' %}
<select>
    {% for perm in current_permissions %}
        <option>{{ perm }}</option>
    {% endfor %}
</select>
    </p>
{#    {{ perms.all }}#}
{#    <p>{{ request }}</p>#}

{% endif %}

            <p style="text-align: center">{% trans 'Logged as ' %}<b>{{ user.username }}</b></p>
<form method="post" id="signForm" data-regions-url="{% url 'geo:ajax_load_regions' %}" novalidate> <!-- necessary -->
{% csrf_token %}
    <h3 class="h3">{% trans 'Wine sign creation form' %}</h3>
        {{ form }}
{% if not user.is_authenticated %}
    <p>{% trans "Your account doesn't have access to this page. Please login with an account that has access to proceed. " %}</p>
{% endif %}
{% if user.is_authenticated and not perms.accounts.create_sign %}
    <p style="text-align: center">{% trans "ou have no permission to do this. You can ask host owner for privileges. And it seems only admin can work with this. " %}Y</p>
{% endif %}
<input class="btn-primary" type="submit" value="{{ form.button_label }}">
</form>
</div>
{% endblock %}

geography/templates/index.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
{% trans 'This is a navigation page. Welcome.' %}


<p>{% trans 'Use links: ' %}</p>
<p class="h6">1) <a href="{% url 'geo:create_sign' %}">{% trans 'Wine sign creation form' %}</a></p>
<p class="h6">2) <a href="{% url 'geo:view' %}">{% trans 'View wine database' %}</a></p>

{% if not user.is_authenticated %}
<p>{% trans "Currently you're not logged in." %}</p>
{% else %}
{% trans "You're logged in as " %}<div style="color: #ba8b00; display: inline">{{ user.username }}</div>
{% endif %}
<br><br>
    <p><a href="{% url 'accounts:login' %}">{% trans 'Login' %}</a></p>
    <p><a href="{% url 'accounts:logout' %}">{% trans 'Logout' %}</a></p>
    <p><a href="{% url 'accounts:register' %}">{% trans 'Register' %}</a></p>
    {% if 'can_translate' in perms %}
    <a href="{% url 'rosetta-file-list-redirect' %}">{% trans 'Make translations...' %}</a>
    {% endif %}
    <p>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    </p>
{% endblock %}

geography/templates/search_results.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your view.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}
<h4 class="text-center">{{ error_msg }}</h4>
<form action="{% url 'geo:create_sign' %}" method="post" enctype="multipart/form-data"> <!-- necessary -->
{% csrf_token %} <!-- necessary -->
<div style="width: 50%; margin: auto">
{% for item in object_list %}
<div class="wine_sign_record">
    <p>{% trans 'Item # - ' %}{{ item.id }}</p>
    <p>{% trans 'Country -' %} {{ item.country }}</p>
    <p>{% trans 'Region -' %} {{ item.region }}</p>
    <p>{% trans 'Area -' %} {{ item.area }}</p>
    <p>{% trans 'Quality mark -' %} {{ item.quality_mark }}</p>
    <p>{% trans 'Sign -' %} <b>{{ item.sign }}</b></p>
</div>
{% endfor %}
    {% if articles.has_previous %}
        <a href="?page={{ articles.previous_page_number }}">←</a>
    {% endif %}
    {% if articles.has_next %}
        <a href="?page={{ articles.next_page_number }}">→</a>
    {% endif %}

</div>
</form>
{% endblock %}

geography/templates/view.html
{% extends "base.html" %}{% load i18n %}
{% load static %}
{% block body %}
    <p>{% trans "Hey, I'm your view.html!" %}</p>
    <a href="{% url 'index' %}">{% trans 'Back to Index' %}</a>
    <br>
    <a href="{% url 'geo:create_sign' %}">{% trans 'Back to sign creation' %}</a>
    {% include "inc/include.html" %}
<h4 class="text-center">{{ error_msg }}</h4>
<form action="{% url 'geo:create_sign' %}" method="post" enctype="multipart/form-data"> <!-- necessary -->
{% csrf_token %} <!-- necessary -->
<div style="width: 50%; margin: auto">
{% for item in object_list %}
<div class="wine_sign_record">
    <p>{% trans 'Item # - ' %}{{ item.id }}</p>
    <p>{% trans 'Country -' %} {{ item.country }}</p>
    <p>{% trans 'Region -' %} {{ item.region }}</p>
    <p>{% trans 'Area -' %} {{ item.area }}</p>
    <p>{% trans 'Quality mark -' %} {{ item.quality_mark }}</p>
    <p>{% trans 'Sign -' %} <b>{{ item.sign }}</b></p>
</div>
{% endfor %}
    {% if articles.has_previous %}
        <a href="?page={{ articles.previous_page_number }}">←</a>
    {% endif %}
    {% if articles.has_next %}
        <a href="?page={{ articles.next_page_number }}">→</a>
    {% endif %}

</div>
</form>
{% include 'inc/uni_form.html' %}
{% endblock %}